function Hd = KaiserFIR_Filter
%KAISERFIR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 28-Dec-2019 17:31:32

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N    = 60;       % Order
Fc1  = 300;      % First Cutoff Frequency
Fc2  = 500;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.55;     % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'stop', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
